### ISSUE TITLE
Change Fortran source file suffix to .f90

### ISSUE THREAD

**Issue by Beliavsky** [jvrglr/Biased-versus-unbiased-codes#1]
Please consider changing the source file suffixes from .f08 to .f90.
The .f90 suffix means that the source code is free format, not that
the code conforms to the Fortran 90 standard. Code that uses the .f90
suffix can use features from any Fortran standard. All Fortran
compilers recognize .f90 as a suffix indicating free source form, but
some may not recognize a suffix such as .f95, .f03, .f08, or .f18.
Some users may have build tools that do not recognize suffixes other
than .f90. Most Fortran source code on GitHub that uses features from
a standard more recent than Fortran 90 still uses the .f90 suffix.

**Comment by jvrglr** [comment]
Dear Beliavsky,

Thank you very much for your comment. I initially believed that `.f08` was also standard for free source form, but as you pointed out, I've realized that this may not be true for many compilers. I appreciate your recommendation, and I will make the necessary changes by using the suffix `.f90`.

Thank you,

Javier.
